language: python
python:
  - 2.6
  - 2.7
install:
    - pip install coveralls --use-mirrors
    - pip install -r requirements.pip --use-mirrors
script:
    - coverage run --source=malva `which trial` malva
after_success:
    - coveralls